development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: edunjoroge@gmail.com
  :password: 07091986
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: edunjoroge@gmail.com
  :password: 07091986
  :enable_starttls_auto: true